apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ include "fastapi-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ecommerce
    version: {{ .Chart.AppVersion }}
data:
  password: YWRtaW4xMjM=
type: Opaque
