kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    app: ecommerce
    version: {{ .Chart.AppVersion }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: postgres-pv
