apiVersion: v1
kind: Secret
metadata:
  name: celery-secret
  namespace: ecommerce-fastapi
  labels:
    app: ecommerce
data:
  REDIS_HOST: cmVkaXMtc2VydmljZQo=
  REDIS_PORT: NjM3OQo=
  REDIS_DB: MAo=
