apiVersion: batch/v1
kind: Job
metadata:
  name: fastapi-migrations
  namespace: ecommerce-fastapi
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: migration-container
          image: haitham2169s/ecommerce-fastapi:1.0
          command:
            - sh
            - -c
            - |
              aerich init -t ecommerce.db.TORTOISE_ORM
              aerich init-db
              aerich migrate
              aerich upgrade
          envFrom:
            - secretRef:
                name: migration-secret
      initContainers:
        - name: init-postgres-service
          image: postgres:13
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432; do echo waiting for database; sleep 2; done;",
            ]
      restartPolicy: OnFailure
  backoffLimit: 15
