apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ecommerce-fastapi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: postgres-disk
    fsType: ext4
