apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret-{{ include "fastapi-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ecommerce
    version: {{ .Chart.AppVersion }}
data:
  DATABASE_USERNAME: YWRtaW4K
  DATABASE_PASSWORD: YWRtaW4xMjMK
  DATABASE_HOST: cG9zdGdyZXMtc2VydmljZQo=
  DATABASE_PORT: NTQzMgo=
  DATABASE_NAME: ZWNvbW1lcmNlZGIK
