apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce-fastapi
  labels:
    app: ecommerce
data:
  DATABASE_USERNAME: YWRtaW4K
  DATABASE_PASSWORD: YWRtaW4xMjMK
  DATABASE_HOST: cG9zdGdyZXMtc2VydmljZQo=
  DATABASE_NAME: ZWNvbW1lcmNlZGIK
